version: '3.8'

services:
  # Database - PostgreSQL 16
  db:
    image: postgres:16-alpine
    container_name: crm-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE:-dormitory_management}
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - crm-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-postgres} -d ${DB_DATABASE:-dormitory_management}"]
      timeout: 20s
      retries: 5

  # Backend API - Laravel
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crm-api
    restart: unless-stopped
    ports:
      - "${API_PORT:-8000}:8000"
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage
    environment:
      APP_ENV: ${APP_ENV:-production}
      APP_DEBUG: ${APP_DEBUG:-false}
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: ${DB_DATABASE:-dormitory_management}
      DB_USERNAME: ${DB_USERNAME:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-password}
      CACHE_STORE: file
      SESSION_DRIVER: file
      QUEUE_CONNECTION: sync
    depends_on:
      db:
        condition: service_healthy
    networks:
      - crm-network

volumes:
  postgres_data:

networks:
  crm-network:
    external: true