services:
  # Local Nginx Reverse Proxy (simulating production setup)
  nginx-proxy:
    image: nginx:alpine
    container_name: crm-nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8000:8000"
    volumes:
      - ./docker/nginx-proxy.conf:/etc/nginx/nginx.conf:ro
      - ./docker/ssl:/etc/nginx/ssl:ro
    depends_on:
      - api
      - frontend
    networks:
      - it_services_net

  # Frontend - Vue.js (for dorm.sdu.edu.kz)
  frontend:
    image: nginx:alpine
    container_name: crm-frontend
    restart: unless-stopped
    volumes:
      - ../crm-front/dist:/usr/share/nginx/html:ro
      - ../crm-front/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - it_services_net

  # Database - PostgreSQL 16
  db:
    image: postgres:16-alpine
    container_name: crm-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE:-dormitory_management}
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - it_services_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-postgres} -d ${DB_DATABASE:-dormitory_management}"]
      timeout: 20s
      retries: 5

  # Backend API - Laravel (for api.dorm.sdu.edu.kz)
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crm-api
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage
    environment:
      APP_ENV: ${APP_ENV:-local}
      APP_DEBUG: ${APP_DEBUG:-true}
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: ${DB_DATABASE:-dormitory_management}
      DB_USERNAME: ${DB_USERNAME:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-password}
      CACHE_STORE: file
      SESSION_DRIVER: file
      QUEUE_CONNECTION: sync
    depends_on:
      db:
        condition: service_healthy
    networks:
      - it_services_net

volumes:
  postgres_data:

networks:
  it_services_net:
    external: true