version: '3.8'

services:
  # Development services
  composer:
    image: composer:2
    container_name: dormitory-management-composer
    working_dir: /app
    volumes:
      - .:/app
    command: composer install
    profiles:
      - dev
      - test
      - build

  migrate:
    image: php:8.2-cli
    container_name: dormitory-management-migrate
    working_dir: /app
    volumes:
      - .:/app
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE:-dormitory_management}
      DB_USERNAME: ${DB_USERNAME:-root}
      DB_PASSWORD: ${DB_PASSWORD:-password}
    depends_on:
      - db
    command: sh -c "php artisan migrate:fresh --seed"
    profiles:
      - dev
      - production

  seed:
    image: php:8.2-cli
    container_name: dormitory-management-seed
    working_dir: /app
    volumes:
      - .:/app
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE:-dormitory_management}
      DB_USERNAME: ${DB_USERNAME:-root}
      DB_PASSWORD: ${DB_PASSWORD:-password}
    depends_on:
      - db
    command: sh -c "php artisan db:seed"
    profiles:
      - dev

  test:
    image: php:8.2-cli
    container_name: dormitory-management-test
    working_dir: /app
    volumes:
      - .:/app
    environment:
      APP_ENV: testing
      DB_CONNECTION: sqlite
      DB_DATABASE: ":memory:"
    depends_on:
      - composer
    command: php artisan test
    profiles:
      - test

  # Development server
  dev:
    image: php:8.2-cli
    container_name: dormitory-management-dev
    working_dir: /app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      APP_ENV: local
      APP_DEBUG: true
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE:-dormitory_management}
      DB_USERNAME: ${DB_USERNAME:-root}
      DB_PASSWORD: ${DB_PASSWORD:-password}
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - db
      - redis
      - composer
    command: sh -c "php -S 0.0.0.0:8000 -t public"
    profiles:
      - dev

  # Production services
  app:
    image: php:8.2-fpm
    container_name: dormitory-management-app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
    environment:
      APP_ENV: production
      APP_DEBUG: false
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE:-dormitory_management}
      DB_USERNAME: ${DB_USERNAME:-root}
      DB_PASSWORD: ${DB_PASSWORD:-password}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PHP_MEMORY_LIMIT: 512M
      PHP_UPLOAD_MAX_FILESIZE: 20M
      PHP_POST_MAX_SIZE: 20M
    depends_on:
      - db
      - redis
    profiles:
      - production

  nginx:
    image: nginx:alpine
    container_name: dormitory-management-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./public:/var/www/html/public:ro
      - ./storage:/var/www/html/storage:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - app
    profiles:
      - production

  # Database
  db:
    image: mysql:8.0
    container_name: dormitory-management-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-dormitory_management}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_USER: ${DB_USERNAME:-root}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d:ro
    command: --default-authentication-plugin=mysql_native_password

  # Redis for caching and sessions
  redis:
    image: redis:alpine
    container_name: dormitory-management-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # Mailhog for email testing in development
  mailhog:
    image: mailhog/mailhog:latest
    container_name: dormitory-management-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    profiles:
      - dev

volumes:
  mysql_data:
  redis_data: